/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayrollNewRouteImport } from './routes/payroll.new'
import { Route as PayInvoiceIdRouteImport } from './routes/pay.$invoiceId'

const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollNewRoute = PayrollNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PayrollRoute,
} as any)
const PayInvoiceIdRoute = PayInvoiceIdRouteImport.update({
  id: '/pay/$invoiceId',
  path: '/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/invoices': typeof InvoicesRoute
  '/onboard': typeof OnboardRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/payroll/new': typeof PayrollNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/invoices': typeof InvoicesRoute
  '/onboard': typeof OnboardRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/payroll/new': typeof PayrollNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/invoices': typeof InvoicesRoute
  '/onboard': typeof OnboardRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/payroll/new': typeof PayrollNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim'
    | '/credit'
    | '/dashboard'
    | '/explore'
    | '/invoices'
    | '/onboard'
    | '/payroll'
    | '/pay/$invoiceId'
    | '/payroll/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim'
    | '/credit'
    | '/dashboard'
    | '/explore'
    | '/invoices'
    | '/onboard'
    | '/payroll'
    | '/pay/$invoiceId'
    | '/payroll/new'
  id:
    | '__root__'
    | '/'
    | '/claim'
    | '/credit'
    | '/dashboard'
    | '/explore'
    | '/invoices'
    | '/onboard'
    | '/payroll'
    | '/pay/$invoiceId'
    | '/payroll/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimRoute: typeof ClaimRoute
  CreditRoute: typeof CreditRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  InvoicesRoute: typeof InvoicesRoute
  OnboardRoute: typeof OnboardRoute
  PayrollRoute: typeof PayrollRouteWithChildren
  PayInvoiceIdRoute: typeof PayInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll/new': {
      id: '/payroll/new'
      path: '/new'
      fullPath: '/payroll/new'
      preLoaderRoute: typeof PayrollNewRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/pay/$invoiceId': {
      id: '/pay/$invoiceId'
      path: '/pay/$invoiceId'
      fullPath: '/pay/$invoiceId'
      preLoaderRoute: typeof PayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PayrollRouteChildren {
  PayrollNewRoute: typeof PayrollNewRoute
}

const PayrollRouteChildren: PayrollRouteChildren = {
  PayrollNewRoute: PayrollNewRoute,
}

const PayrollRouteWithChildren =
  PayrollRoute._addFileChildren(PayrollRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimRoute: ClaimRoute,
  CreditRoute: CreditRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  InvoicesRoute: InvoicesRoute,
  OnboardRoute: OnboardRoute,
  PayrollRoute: PayrollRouteWithChildren,
  PayInvoiceIdRoute: PayInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
